######################################################################
##
## Filename: tb_RS232Txd.udo
## Created on: Sat Dec 07 10:50:01 PM Malay Peninsula Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
